title: "#MBSC2025"
url: https://www.marinabaycountdown.gov.sg
favicon: /images/MBSC_logo__RGB_Compact_.png
colors:
  primary-color: "#14857a"
  secondary-color: "#4f758b"
  media-colors:
    - title: media-color-one
      color: "#f5a623"
    - title: media-color-two
      color: "#37a390"
    - title: media-color-three
      color: "#9b9b9b"
    - title: media-color-four
      color: "#f8e71c"
    - title: media-color-five
      color: "#b8e986"
description: Find out more about Marina Bay Singapore Countdown
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d3gz5vdw020713.amplifyapp.com
prod: https://master.d3gz5vdw020713.amplifyapp.com
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics: ""
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: news
